### ISSUE TITLE
Python 3 support for the OS X package

### ISSUE THREAD

**Issue by dessant** [kivy/kivy-sdk-packager#10]
Port of https://github.com/kivy/kivy/issues/3404.

**Comment by Twangist** [comment]
Is this closed because Kivy in fact works on OS X with Py 3.4.3? If so, what's the solution to the problem? And if it doesn't work, why is the issue closed?

**Comment by dessant** [comment]
@Twangist oO, this issue was just opened.

**Comment by Twangist** [comment]
Ah, misunderstood. Good! Thanks for clarifying.

**Comment by akshayaurora** [comment]
Solved by 0f9dddb1986952361149a4e4bfbce0693f319ceb
