### ISSUE TITLE
git-merge: not found

### ISSUE THREAD

**Issue by dessant** [kivy/kivy-sdk-packager#12]
```
/e/dev/envs/py34_x86/kivy (master)
$ git pull
E:\dev\envs\py34_x86\MinGW\msysgit/libexec/git-core\git-pull: line 321: exec: git-merge: not found
fatal: 'pull' appears to be a git command, but we were not
able to execute it. Maybe git-pull is broken?
```

**Comment by dessant** [comment]
I'm not sure if this is a git or packager bug, we could also use the new git for windows repo https://github.com/git-for-windows/git, msysgit is now deprecated.

https://github.com/kivy/kivy-sdk-packager/blob/4d218b5ec4d2c268885352dcbf2296bcb3dfa816/win/kivy_win_sdk.py#L713

**Comment by dessant** [comment]
On @matham's suggestion i've ran `tools\link_msysgit.bat` from a win shell and it solved the issue.

**Comment by tito** [comment]
This one make me angry when deploying on customer theses days :)
Just a workaround:

    git fetch -a
    git reset --hard origin/master

Works only when you want to get your latest master, it doesn't merge anything.

**Comment by matham** [comment]
We won't be distributing git or anything anymore with the new wheels. So this should not be an issue.
