### ISSUE TITLE
Windows portable package conflicts with installed Python

### ISSUE THREAD

**Issue by NumesSanguis** [kivy/kivy-sdk-packager#13]
When you download Kivy from the following page for Windows (tested with Python 3.4): http://kivy.org/#download
and the host Windows system already has Python (3.4) installed with Environment Variables:
Path: C:\Python34\;C:\Python34\Scripts;
PYTHONPATH: C:\Python34;C:\Python34\Lib;C:\Python34\DLLs;C:\Python34\Lib\lib-tk;C:\Python34\Lib\site-packages;C:\Python34\Lib\site-packages\opencv

the kivy.bat uses the system's Python instead of the Python inside the portable package.

It would be nice that both Python's can co-exist without the need to remove Python from the Systems's Environment Variables.

**Comment by matham** [comment]
What does it say when you do `echo %PATH%`. Also, what does `where python` output?

**Comment by NumesSanguis** [comment]
I already removed the environmental variables, but this is what I got before when running kivy-3.4.bat:
http://pastebin.com/eAM4bN5c

**Comment by d0ntreadthis** [comment]
I'm having the same problem. I'm using Python 2.7 and have removed my Path and PYTHONPATH environment variables. Ran pip install pyinstaller from the kivy-2.7.bat. Now when I try to run pyinstaller it says "failed to create process"

**Comment by d0ntreadthis** [comment]
I've redownlaoded Kivy portable, and now when I run pyinstaller testapp.spec from kivy-2.7.bat I get the original error: http://pastebin.com/sgJhuLqJ
Here's the spec file http://pastebin.com/4WGLs3NB

**Comment by matham** [comment]
This is unrelated to the original issue. And it's because the docs are for kivy master but you probably used a older version. Regarding the original issue, we're switching to wheels so this should not an issue.
