### ISSUE TITLE
sudo apt-get install kivy-examples broken package

### ISSUE THREAD

**Issue by NumesSanguis** [kivy/kivy-sdk-packager#15]
While on Kivy-daily and updated today, when I do: sudo apt-get install kivy-examples
I get the error:

sudo apt-get install kivy-examples
[sudo] password for xxx:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 kivy-examples : Depends: python-kivy (= 1.9.1-dev~daily0+201508211501-3006-testing66~ubuntu14.04.1) but 1.9.1-dev~daily0+201510162146-3105-testing75~ubuntu14.04.1 is to be installed
E: Unable to correct problems, you have held broken packages.

**System**: Ubuntu 14.04, Python 2.7

**Comment by thopiekar** [comment]
Should be fixed soon. There was a file "missing" in kivy/kivy, which has been removed now.
Corrected it and fresh packages are on the go.

Wisjh you happy hacking and please give a short feedback, whether it is fixed so I can close this issue :)

**Comment by NumesSanguis** [comment]
Yep, it's fixed :)
