### ISSUE TITLE
'python.exe' not recognized as a command

### ISSUE THREAD

**Issue by okayman-kivy** [kivy/kivy-sdk-packager#16]
Hello.
I have installed Kivy with the following self extracting file : http://kivy.org/downloads/1.9.0/Kivy-1.9.0-py2.7-win32-x86.exe
Then I have copied kivy-27.bat in SendTo folder.
Then I tried to start Kivy-1.9.0-py2.7-win32-x86\kivy27\examples\demo\showcase\main.py just like the demo using send to, and it returned the error 'python.exe' not recognized as a command.
Did I miss something?

I also have another python (with kivy) installed because it was the package. Do you know if there is any easy & safe soluce to install kivy in my main python folder, on windows 7?

Thank you! :smile:

**Comment by bionoid** [comment]
You should not *copy* the file to SendTo, but make a shortcut

**Comment by okayman-kivy** [comment]
Ah correct my bad.
