### ISSUE TITLE
Kivy 1.9 on Windows 7 - no module named kivy

### ISSUE THREAD

**Issue by OortJacek** [kivy/kivy-sdk-packager#17]
Hello, I have huge problem with run kivy on windows. I have uninstalled all my previous python version but still nothing. I also have tried run with "open with" and "send to" and directly from kivy_bash.bat

Everytime I get error "no module named kivy".

I am trying to run example "hello world" button.

http://pastebin.com/q9U57cVj

Don't work with 3.4 neither 2.7 version.

**Comment by matham** [comment]
We will providing wheels from now on. And anyway, we cannot troubleshoot this kind of issue here. You should ask on IRC if you still have issues.
