### ISSUE TITLE
Revert revrted too much

### ISSUE THREAD

**Issue by matham** [kivy/kivy-sdk-packager#23]
Hey @thopiekar, it seems the revert you did removed all the recent changes to the win folder and probably mac as well. Can you unrevert the revert and then only revert specific commits?

**Comment by thopiekar** [comment]
Sure, I hoped I could restore my wrong merge by git revert, but it reverted too much.

**Comment by akshayaurora** [comment]
@thopiekar ok if we force push to before you started committing?

**Comment by thopiekar** [comment]
Sorry, already done :/ You can do a force push and make it clean..

**Comment by akshayaurora** [comment]
@thopiekar no worries if you can fix it on top then it's ok.

**Comment by thopiekar** [comment]
Is it ok now?

**Comment by matham** [comment]
Yep, should be fine.

**Comment by thopiekar** [comment]
Puhh, so good that it worked ^^

**Comment by akshayaurora** [comment]
:relaxed:
