### ISSUE TITLE
How to package garden dependencies (on OSX)

### ISSUE THREAD

**Issue by johanneshk** [kivy/kivy-sdk-packager#24]
Hi,

so I'm trying to package my app with a garden dep (matplotlib). How do I do that? 
I installed matplotlib with --app in the app dir but is that enough? Doing 'kivy main.py' works without problems. 
I can successfully run package_app.py, but launching the .app does not work.
I then randomly launched 'myapp.app/Contents/MacOS/Kivy' which apparently prints some debugging info and here the following error appears:
```
...
 ValueError: 'path/to/myapp.app/Contents/Resources/yourapp/libs/garden/garden.matplotlib/__init__.py/__init__.pyc' is not a package
```

So I'm assuming something's wrong with my garden dependencies. Any ideas?

**Comment by akshayaurora** [comment]
@johanneshk can you test with `--gardendeps=matplotlib,otherdeps`

**Comment by johanneshk** [comment]
@akshayaurora no sorry same behaivor as before. Plus in line 200 of package_app.py is a small mistake:
```
    if gardendeps:
        install_garden_deps(appname, deps)
```

**Comment by johanneshk** [comment]
Once pull request https://github.com/kivy/kivy-sdk-packager/pull/25 has been merged, this issue can be closed.
