### ISSUE TITLE
Environment variables in 'script' use names of dir and files that do not exist in Resources folder

### ISSUE THREAD

**Issue by rogererens** [kivy/kivy-sdk-packager#3]
In the file ```Resources/script``` these environment variables, amongst others, are created:
```
export DYLD_FALLBACK_LIBRARY_PATH="${SCRIPT_PATH}/lib"
export LD_PRELOAD_PATH="${SCRIPT_PATH}/lib"
export GST_REGISTRY="${SCRIPT_PATH}/gst.registry"
export KIVY_HOME="${SCRIPT_PATH}/.kivy"
```
Whereas the entries ```lib```, ```gst.registry```, and ```.kivy``` do not exist in ```Resources``` which is the ```${SCRIPT_PATH}``` in Kivy-1.9.0-osx.dmg.

**Comment by tito** [comment]
`GST_REGISTRY` and `KIVY_HOME` are necessary, but not needed to exist when package is shipped. They will be created on the fly by the running app when needed.
As for the first two, this can be handy when you use external libraries, but we don't have any when we ship the application.

So far, no need to remove them :)
