### ISSUE TITLE
The SDL2 version changes break the daily PPA

### ISSUE THREAD

**Issue by dolang** [kivy/kivy-sdk-packager#39]
https://github.com/kivy/kivy-sdk-packager/blob/db9015b890aa04b6b6b2f33df5e7ca5520350001/linux/debian/daily/control#L194-L197

I don't quite understand why, but if you don't specify the full versions, it breaks package dependency resolution.

Please revert to:
```
         libsdl2-2.0-0,
         libsdl2-image-2.0-0 | python-gi | python3-pil,
         libsdl2-mixer-2.0-0 | libgstreamer-1.0,
         libsdl2-ttf-2.0-0 | python3-pil,
```

And maybe `libgstreamer-1.0-0`, too.

**Comment by dolang** [comment]
Still broken with  7582d96, it's as if the changes weren't incorporated in the built package.

I'm still seeing `libsdl2*-2.0` instead of `libsdl2*-2.0-0` in the `Depends` section (as well as the build log).

**Comment by tshirtman** [comment]
i'm really confused by this, the recipe in launchpad is up to date, and the source package doesn't try to install these bad package, but when i open the resulting deb package, in the control file, the Depends line does contain the wrong names, i'm not sure what could cause this, i'll try to rebuild once more, in case it's a caching issue on launchpad side.

**Comment by dolang** [comment]
If anyone else ever stumbles on this:

Turns out the `kivy-sdk-packager` repository gets pulled in periodically, not immediately. Revision 7582d96 works now, after everything has been refreshed and rebuilt.

**Comment by thopiekar** [comment]
Yes, this happens every 5 hours if I'm not wrong. The files here (GitHub)
need to get synced with a mirror at launchpad.net (Canonical).

**Comment by tshirtman** [comment]
I was surprised because i'm pretty sure i clicked a button to reload the recipe from git before the builds, but glad it's fixed now.
