### ISSUE TITLE
Path with yourapp in package-app.sh on OS X

### ISSUE THREAD

**Issue by martinsik** [kivy/kivy-sdk-packager#6]
I tried to use `package-app.sh` to generate .app but I'm not sure about the output directory structure. Running:

```
$ package-app.sh /path/to/my/project
```

The result `project.app` contains my code in `/Contents/Resources/yourapp/project` but Kivy expects `main.py` in `/Contents/Resources/yourapp/` so it won't run.

I think the problem is [line 31 in package-app.sh](https://github.com/kivy/kivy-sdk-packager/blob/master/osx/package-app.sh#L31) where:

```
cp -a $1 ${APPPATH}/Contents/Resources/yourapp
```
Should be:
```
cp -a $1/* ${APPPATH}/Contents/Resources/yourapp
```

**Comment by tito** [comment]
You should pass your application directory that contain main.py as a first argument, not a file, or parent directory.
And your application will be copied as yourapp, not yourapp/appdir.
